image: node:latest

cache:
  paths:
    - ./node_modules

pages:
  stage: deploy
  before_script:
    - npm config set registry http://artefact-repo.pole-emploi.intra/artifactory/api/npm/npm-public
    - npm install stencil
  script:
    - npm start
  artifacts:
    paths:
      - www
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
