/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface Pea11ySnippet {
      'uris': any;
    }
  }

  interface HTMLPea11ySnippetElement extends StencilComponents.Pea11ySnippet, HTMLStencilElement {}

  var HTMLPea11ySnippetElement: {
    prototype: HTMLPea11ySnippetElement;
    new (): HTMLPea11ySnippetElement;
  };
  interface HTMLElementTagNameMap {
    'pea11y-snippet': HTMLPea11ySnippetElement;
  }
  interface ElementTagNameMap {
    'pea11y-snippet': HTMLPea11ySnippetElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'pea11y-snippet': JSXElements.Pea11ySnippetAttributes;
    }
  }
  namespace JSXElements {
    export interface Pea11ySnippetAttributes extends HTMLAttributes {
      'uris'?: any;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;