/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface Pea11yRating {
        "classEmpty": string;
        "classHover": string;
        "classSelected": string;
        "label": string;
        "labelledby": string;
        "max": number;
        "readonly": boolean;
        "resultText": string;
        "setValue": (newValue: number) => Promise<void>;
        "showText": boolean;
        "textValues": any;
        "value": number;
    }
    interface Pea11ySnippet {
        "dataCss": string;
        "dataHtml": string;
        "dataJs": string;
    }
    interface Pea11yTabs {
        "label": string;
        "tabsNames": any;
    }
    interface Pea11yTooltip {
        "sameAsTxt": boolean;
        "tooltipLabel": string;
    }
    interface Pea11yUxstars {
        "imgEmpty": string;
        "imgFull": string;
        "imgSize": any;
        "label": string;
        "value": number;
    }
}
export interface Pea11yRatingCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPea11yRatingElement;
}
declare global {
    interface HTMLPea11yRatingElement extends Components.Pea11yRating, HTMLStencilElement {
    }
    var HTMLPea11yRatingElement: {
        prototype: HTMLPea11yRatingElement;
        new (): HTMLPea11yRatingElement;
    };
    interface HTMLPea11ySnippetElement extends Components.Pea11ySnippet, HTMLStencilElement {
    }
    var HTMLPea11ySnippetElement: {
        prototype: HTMLPea11ySnippetElement;
        new (): HTMLPea11ySnippetElement;
    };
    interface HTMLPea11yTabsElement extends Components.Pea11yTabs, HTMLStencilElement {
    }
    var HTMLPea11yTabsElement: {
        prototype: HTMLPea11yTabsElement;
        new (): HTMLPea11yTabsElement;
    };
    interface HTMLPea11yTooltipElement extends Components.Pea11yTooltip, HTMLStencilElement {
    }
    var HTMLPea11yTooltipElement: {
        prototype: HTMLPea11yTooltipElement;
        new (): HTMLPea11yTooltipElement;
    };
    interface HTMLPea11yUxstarsElement extends Components.Pea11yUxstars, HTMLStencilElement {
    }
    var HTMLPea11yUxstarsElement: {
        prototype: HTMLPea11yUxstarsElement;
        new (): HTMLPea11yUxstarsElement;
    };
    interface HTMLElementTagNameMap {
        "pea11y-rating": HTMLPea11yRatingElement;
        "pea11y-snippet": HTMLPea11ySnippetElement;
        "pea11y-tabs": HTMLPea11yTabsElement;
        "pea11y-tooltip": HTMLPea11yTooltipElement;
        "pea11y-uxstars": HTMLPea11yUxstarsElement;
    }
}
declare namespace LocalJSX {
    interface Pea11yRating {
        "classEmpty"?: string;
        "classHover"?: string;
        "classSelected"?: string;
        "label"?: string;
        "labelledby"?: string;
        "max"?: number;
        "onPea11yRatingChange"?: (event: Pea11yRatingCustomEvent<any>) => void;
        "onPea11yRatingHover"?: (event: Pea11yRatingCustomEvent<any>) => void;
        "onPea11yRatingLeave"?: (event: Pea11yRatingCustomEvent<any>) => void;
        "readonly"?: boolean;
        "resultText"?: string;
        "showText"?: boolean;
        "textValues"?: any;
        "value"?: number;
    }
    interface Pea11ySnippet {
        "dataCss"?: string;
        "dataHtml"?: string;
        "dataJs"?: string;
    }
    interface Pea11yTabs {
        "label"?: string;
        "tabsNames"?: any;
    }
    interface Pea11yTooltip {
        "sameAsTxt"?: boolean;
        "tooltipLabel"?: string;
    }
    interface Pea11yUxstars {
        "imgEmpty"?: string;
        "imgFull"?: string;
        "imgSize"?: any;
        "label"?: string;
        "value"?: number;
    }
    interface IntrinsicElements {
        "pea11y-rating": Pea11yRating;
        "pea11y-snippet": Pea11ySnippet;
        "pea11y-tabs": Pea11yTabs;
        "pea11y-tooltip": Pea11yTooltip;
        "pea11y-uxstars": Pea11yUxstars;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pea11y-rating": LocalJSX.Pea11yRating & JSXBase.HTMLAttributes<HTMLPea11yRatingElement>;
            "pea11y-snippet": LocalJSX.Pea11ySnippet & JSXBase.HTMLAttributes<HTMLPea11ySnippetElement>;
            "pea11y-tabs": LocalJSX.Pea11yTabs & JSXBase.HTMLAttributes<HTMLPea11yTabsElement>;
            "pea11y-tooltip": LocalJSX.Pea11yTooltip & JSXBase.HTMLAttributes<HTMLPea11yTooltipElement>;
            "pea11y-uxstars": LocalJSX.Pea11yUxstars & JSXBase.HTMLAttributes<HTMLPea11yUxstarsElement>;
        }
    }
}
